require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GroupssesController do

  # This should return the minimal set of attributes required to create a valid
  # Groupss. As you add validations to Groupss, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GroupssesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all groupsses as @groupsses" do
      groupss = Groupss.create! valid_attributes
      get :index, {}, valid_session
      assigns(:groupsses).should eq([groupss])
    end
  end

  describe "GET show" do
    it "assigns the requested groupss as @groupss" do
      groupss = Groupss.create! valid_attributes
      get :show, {:id => groupss.to_param}, valid_session
      assigns(:groupss).should eq(groupss)
    end
  end

  describe "GET new" do
    it "assigns a new groupss as @groupss" do
      get :new, {}, valid_session
      assigns(:groupss).should be_a_new(Groupss)
    end
  end

  describe "GET edit" do
    it "assigns the requested groupss as @groupss" do
      groupss = Groupss.create! valid_attributes
      get :edit, {:id => groupss.to_param}, valid_session
      assigns(:groupss).should eq(groupss)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Groupss" do
        expect {
          post :create, {:groupss => valid_attributes}, valid_session
        }.to change(Groupss, :count).by(1)
      end

      it "assigns a newly created groupss as @groupss" do
        post :create, {:groupss => valid_attributes}, valid_session
        assigns(:groupss).should be_a(Groupss)
        assigns(:groupss).should be_persisted
      end

      it "redirects to the created groupss" do
        post :create, {:groupss => valid_attributes}, valid_session
        response.should redirect_to(Groupss.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved groupss as @groupss" do
        # Trigger the behavior that occurs when invalid params are submitted
        Groupss.any_instance.stub(:save).and_return(false)
        post :create, {:groupss => { "name" => "invalid value" }}, valid_session
        assigns(:groupss).should be_a_new(Groupss)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Groupss.any_instance.stub(:save).and_return(false)
        post :create, {:groupss => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested groupss" do
        groupss = Groupss.create! valid_attributes
        # Assuming there are no other groupsses in the database, this
        # specifies that the Groupss created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Groupss.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => groupss.to_param, :groupss => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested groupss as @groupss" do
        groupss = Groupss.create! valid_attributes
        put :update, {:id => groupss.to_param, :groupss => valid_attributes}, valid_session
        assigns(:groupss).should eq(groupss)
      end

      it "redirects to the groupss" do
        groupss = Groupss.create! valid_attributes
        put :update, {:id => groupss.to_param, :groupss => valid_attributes}, valid_session
        response.should redirect_to(groupss)
      end
    end

    describe "with invalid params" do
      it "assigns the groupss as @groupss" do
        groupss = Groupss.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Groupss.any_instance.stub(:save).and_return(false)
        put :update, {:id => groupss.to_param, :groupss => { "name" => "invalid value" }}, valid_session
        assigns(:groupss).should eq(groupss)
      end

      it "re-renders the 'edit' template" do
        groupss = Groupss.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Groupss.any_instance.stub(:save).and_return(false)
        put :update, {:id => groupss.to_param, :groupss => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested groupss" do
      groupss = Groupss.create! valid_attributes
      expect {
        delete :destroy, {:id => groupss.to_param}, valid_session
      }.to change(Groupss, :count).by(-1)
    end

    it "redirects to the groupsses list" do
      groupss = Groupss.create! valid_attributes
      delete :destroy, {:id => groupss.to_param}, valid_session
      response.should redirect_to(groupsses_url)
    end
  end

end
