require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpicesController do

  # This should return the minimal set of attributes required to create a valid
  # Spice. As you add validations to Spice, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spices as @spices" do
      spice = Spice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spices).should eq([spice])
    end
  end

  describe "GET show" do
    it "assigns the requested spice as @spice" do
      spice = Spice.create! valid_attributes
      get :show, {:id => spice.to_param}, valid_session
      assigns(:spice).should eq(spice)
    end
  end

  describe "GET new" do
    it "assigns a new spice as @spice" do
      get :new, {}, valid_session
      assigns(:spice).should be_a_new(Spice)
    end
  end

  describe "GET edit" do
    it "assigns the requested spice as @spice" do
      spice = Spice.create! valid_attributes
      get :edit, {:id => spice.to_param}, valid_session
      assigns(:spice).should eq(spice)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spice" do
        expect {
          post :create, {:spice => valid_attributes}, valid_session
        }.to change(Spice, :count).by(1)
      end

      it "assigns a newly created spice as @spice" do
        post :create, {:spice => valid_attributes}, valid_session
        assigns(:spice).should be_a(Spice)
        assigns(:spice).should be_persisted
      end

      it "redirects to the created spice" do
        post :create, {:spice => valid_attributes}, valid_session
        response.should redirect_to(Spice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spice as @spice" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spice.any_instance.stub(:save).and_return(false)
        post :create, {:spice => { "name" => "invalid value" }}, valid_session
        assigns(:spice).should be_a_new(Spice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spice.any_instance.stub(:save).and_return(false)
        post :create, {:spice => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spice" do
        spice = Spice.create! valid_attributes
        # Assuming there are no other spices in the database, this
        # specifies that the Spice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spice.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => spice.to_param, :spice => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested spice as @spice" do
        spice = Spice.create! valid_attributes
        put :update, {:id => spice.to_param, :spice => valid_attributes}, valid_session
        assigns(:spice).should eq(spice)
      end

      it "redirects to the spice" do
        spice = Spice.create! valid_attributes
        put :update, {:id => spice.to_param, :spice => valid_attributes}, valid_session
        response.should redirect_to(spice)
      end
    end

    describe "with invalid params" do
      it "assigns the spice as @spice" do
        spice = Spice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spice.any_instance.stub(:save).and_return(false)
        put :update, {:id => spice.to_param, :spice => { "name" => "invalid value" }}, valid_session
        assigns(:spice).should eq(spice)
      end

      it "re-renders the 'edit' template" do
        spice = Spice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spice.any_instance.stub(:save).and_return(false)
        put :update, {:id => spice.to_param, :spice => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spice" do
      spice = Spice.create! valid_attributes
      expect {
        delete :destroy, {:id => spice.to_param}, valid_session
      }.to change(Spice, :count).by(-1)
    end

    it "redirects to the spices list" do
      spice = Spice.create! valid_attributes
      delete :destroy, {:id => spice.to_param}, valid_session
      response.should redirect_to(spices_url)
    end
  end

end
